# Generated by Django 5.0.1 on 2024-01-27 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_department_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
