# Generated by Django 5.0.1 on 2024-01-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_userinfo_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
