# Generated by Django 5.0.1 on 2024-01-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_alter_userinfo_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(default=20),
        ),
    ]
